---
- name: Deploy ifrri node for centos 7
  hosts: rpm
  become: yes

  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
      
  - name: Install packages for docker
    yum:
      name:
        - epel-release
        - unzip
        - git
        - wget
      state: present
 
  - name: Install python
    yum:
      name:
        - python2-pip
      state: latest

  - name: Install packages for docker
    yum:
      name:
        - python-setuptools
      state: latest
      
  - name: Download sh docker-ce
    get_url:
      url: https://get.docker.com/
      dest: /opt/docker-ce.sh
      mode: '0775'
      
  - name: install docker-ce
    shell: /opt/docker-ce.sh

  - name: all daemons reload
    systemd:
      daemon_reload: yes
 
  - name: Enable and start docker
    systemd:
      name: docker
      enabled: true
      state: started      

  - name: Create work dir to git rep
    file:
      path: /opt/i-free/test0
      state: directory
      mode: '0755'

  - name: Download git repo
    git: 
      repo: 'https://github.com/gytim/ifrri.git'
      dest: /opt/i-free/test0


  - name: Grant permission to build stolonctl
    file:
      path: /opt/i-free/test0/ifrri-swarm/deploy_stolonctl.sh
      mode: u+rwx,g-wx,o-rwx

  - name: build stolonctl
    shell: /opt/i-free/test0/ifrri-swarm/deploy_stolonctl.sh
    args:
      chdir: /opt/i-free/test0/ifrri-swarm
      
  - firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Grant permission to swarm init
    file:
      path: /opt/i-free/test0/ifrri-swarm/init_docker_swarm.sh
      mode: u+rwx,g-wx,o-rwx
      
  - name: Run baby ^)
    shell: /opt/i-free/test0/ifrri-swarm/init_docker_swarm.sh >> /opt/i-free/test0/log.txt
