---
- name: install basic package for using vagrant command on ubuntu 16.04
  hosts: deb
  become: yes
  
  tasks:
  - name: mount cdrom
    shell: mount /dev/cdrom /mount/cdrom
    
  - name: 
    apt: 
       name:
          - linux-headers-generic
          - build-essential 
          - dkms
  
  - name: run V_B_Guest
    shell: /media/cdrom/VBoxLinuxAdditions.run
 
       
